### ISSUE TITLE
As a user, I would like to see possible values of an DatatypeEnumeration

### ISSUE THREAD

**Issue by antoineatstariongroup** [STARIONGROUP/reqifviewer#49]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of reqifviewer
- [x] I have searched [open](https://github.com/STARIONGROUP/reqifviewer/issues) and [closed](https://github.com/STARIONGROUP/reqifviewer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

While inspecting a DatatypeDefinition for a DatatypeEnumeration, no information about all possible values are displayed.
### System Configuration

- ReqIFSharp version:
  - [x] reqifviewer: 2.0.0
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatstariongroup** [comment]
please indicate where and how you would like to see this information

**Comment by antoineatstariongroup** [comment]
After selecting a DatatypeDefinition on the DatatypeDefinition list, we land to the DatatypeDefinition "details" page. I think that have a section on the Properties part would be nice. 
All possible values could be displayed as a bullet list
![image](https://github.com/STARIONGROUP/reqifviewer/assets/97221392/994ccb92-a07b-4f5e-a1c3-61fed6dfb891)
