### ISSUE TITLE
As a user, I would like to see applied EnumValue(s) on an AttributeValueEnumeration

### ISSUE THREAD

**Issue by antoineatstariongroup** [STARIONGROUP/reqifviewer#50]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of reqifviewer
- [x] I have searched [open](https://github.com/STARIONGROUP/reqifviewer/issues) and [closed](https://github.com/STARIONGROUP/reqifviewer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

While inspecting a SpecElement (Specification/SpecObject), on the Attributes list, a blank value is set on case of an AttributeValueEnumeration. It would be nice to see all selected values for the related AttraibuteValueEnumeration

### System Configuration

- ReqIFSharp version:
  - [x] reqifviewer: 2.0.0
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatstariongroup** [comment]
cannot reproduce
